language: node_js
node_js:
- '8'
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.0.0
jobs:
  include:
  - stage: Unit tests
    script:
    - npm run test-unit
  - stage: Integration tests
    script:
    - sudo /etc/init.d/mysql stop
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start 5"
    - sleep 5m
    - http_code=$(curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8081/streamr-core/login/auth); while true; do if [ $http_code = 200 ]; then echo "EE up and running"; break; else echo "EE not receiving connections"; sleep 5; fi; done
    - npm run test-integration

