name: Run eslint and tests

on:
  schedule:
    # run every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Test on node ${{ matrix.node-version }} and ubuntu-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci
      run: npm ci

    - name: eslint
      run: npm run eslint

    - name: clone dev scripts
      run: |
        env
        git clone https://github.com/streamr-dev/streamr-docker-dev.git
        sudo service mysql stop

    - name: start services
      run: |
        sudo ifconfig docker0 10.200.10.1/24
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start ganache

    - name: start logging
      run: |
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh log -f &

    - name: start CPS
      run: |
        sleep 1m
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start community-product
        sleep 1m

    - name: run integration test
      run: npm run test-integration
