name: Run eslint and tests

on:
  schedule:
    # run every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ubuntu-latest
#    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x] # , 12.x]
#        os: [ubuntu-latest, macOS-latest, windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci
      run: npm ci

    - name: eslint
      run: npm run eslint

#    - name: test-unit
#      run: npm run test-unit

    - name: test-integration
      run: |
        git clone https://github.com/streamr-dev/streamr-docker-dev.git
        sudo ifconfig docker0 10.200.10.1/24
        ${GITHUB_WORKSPACE}/streamr-docker-dev/streamr-docker-dev/bin.sh start 5
#      run: echo 'test-integration'
#      run: npm run test-integration

